apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server-deployment
  labels:
    app: iperf3-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: iperf3-server
        image: us-west1-docker.pkg.dev/tigera-marketing/tigera-instruqt/iperf3:latest
        args: ['-s']
        ports:
        - containerPort: 5201
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
spec:
  selector:
    app: iperf3-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-clients
  labels:
    app: iperf3-client
spec:
  replicas: 4
  selector:
    matchLabels:
      app: iperf3-client
  template:
    metadata:
      labels:
        app: iperf3-client
      annotations:
        qos.projectcalico.org/egressBandwidth: "100M"
        qos.projectcalico.org/egressBurst: "300M"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: iperf3-client
        image: us-west1-docker.pkg.dev/tigera-marketing/tigera-instruqt/iperf3:latest
        command: ['/bin/sh', '-c', 'sleep infinity']
        # To benchmark manually: kubectl exec deploy/iperf3-clients -- /bin/sh -c 'iperf3 -c iperf3-server -O5 [-R]'
      terminationGracePeriodSeconds: 0
