apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf2-server-deployment
  labels:
    app: iperf2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf2-server
  template:
    metadata:
      labels:
        app: iperf2-server
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: iperf2-server
        image: us-west1-docker.pkg.dev/tigera-marketing/tigera-instruqt/iperf:latest
        args: ['-s', '-u', '-i1']
        ports:
        - containerPort: 5001
          protocol: TCP
          name: server-tcp
        - containerPort: 5001
          protocol: UDP
          name: server-udp
      terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Service
metadata:
  name: iperf2-server
spec:
  selector:
    app: iperf2-server
  ports:
  - protocol: UDP
    port: 5001
    targetPort: server-udp
    name: iperf2-udp
  - protocol: TCP
    port: 5001
    targetPort: server-tcp
    name: iperf2-tcp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf2-clients
  labels:
    app: iperf2-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iperf2-client
  template:
    metadata:
      labels:
        app: iperf2-client
      annotations:
        qos.projectcalico.org/egressPacketRate: "100"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: iperf2-client
        image: us-west1-docker.pkg.dev/tigera-marketing/tigera-instruqt/iperf:latest
        command: ['/bin/sh', '-c', 'sleep infinity']
        # To benchmark manually: kubectl exec deploy/iperf2-clients -- /bin/sh -c 'iperf -c iperf2-server -u -l1000 -b200M -i1 -t10'
      terminationGracePeriodSeconds: 0
